### ISSUE TITLE
Problem calling Dispose

### ISSUE THREAD

**Issue by Terminators24** [Azure-Samples/Cognitive-Speech-STT-Windows#20]
I'm facing a problem when i try to call the form Close() method inside the Eeventhandler OnResponseReceived: when the form closing rises...
private void MainForm_FormClosing(object sender, FormClosingEventArgs e)
{
            if (micClient != null)
            {
                micClient.Dispose(); //stucks for several seconds
            }

            base.OnClosing(e);
}
the MicrophoneRecognitionClient.Dispose() stucks for serveral seconds. It may take also 10 to 15 seconds.
Hope someone can help me.

**Comment by v-sukssi** [comment]
Is it possible for you to upload the complete sample code.

**Comment by priyaravi20** [comment]
Please use the sample on Github - https://github.com/Azure-Samples/Cognitive-Speech-STT-Windows/tree/master/samples/SpeechRecognitionServiceExample

Priya Rajan
Microsoft
