### ISSUE TITLE
Requires methods or properties for authentication tokens

### ISSUE THREAD

**Issue by hatsunea** [Azure-Samples/Cognitive-Speech-STT-Windows#22]
When the speech is recognized continuously, recognition stops.
I think the reason is because the tokens expired. I want you to create a new property that will give you an outside token. Or, you should have a method to re-fetch the token.

**Comment by v-sukssi** [comment]
Hi 
Could you please share the detailed scenario where you are getting this behavior.

**Comment by priyaravi20** [comment]
SDK auto refetches expired tokens. Please send logs if this is still an issue.
