### ISSUE TITLE
SpeechClient.dll crashed as transcription started.

### ISSUE THREAD

**Issue by leviyakir** [Azure-Samples/Cognitive-Speech-STT-Windows#23]
Build: 1.0.0.3
Dump: https://drive.google.com/file/d/0BwtlfDyTIqVmblV1Ymk2VjJSSGM/view?usp=sharing
Crashing thread is 6044.
Note: I always use 2 instances of DataRecognitionClient concurrently.
Stacktrace:
00=SpeechClient.dll! DllUnregisterServer - 0x00007FF8986E6783, module offset(base): 0x46783(0x7ff8986a0000)
01=SpeechClient.dll! DllUnregisterServer - 0x00007FF8986E744E, module offset(base): 0x4744e(0x7ff8986a0000)
02=SpeechClient.dll! DllUnregisterServer - 0x00007FF8986E8A95, module offset(base): 0x48a95(0x7ff8986a0000)
03=SpeechClient.dll! DllUnregisterServer - 0x00007FF8986E7DD9, module offset(base): 0x47dd9(0x7ff8986a0000)
04=SpeechClient.dll! DllUnregisterServer - 0x00007FF8986E3A8D, module offset(base): 0x43a8d(0x7ff8986a0000)
05=SpeechClient.dll! DllUnregisterServer - 0x00007FF8986E31C8, module offset(base): 0x431c8(0x7ff8986a0000)
06=SpeechClient.dll! DllUnregisterServer - 0x00007FF8986D18DA, module offset(base): 0x318da(0x7ff8986a0000)
07=SpeechClient.dll! DllUnregisterServer - 0x00007FF89870F087, module offset(base): 0x6f087(0x7ff8986a0000)
08=SpeechClient.dll! DllUnregisterServer - 0x00007FF89870EC4D, module offset(base): 0x6ec4d(0x7ff8986a0000)
09=???! ??? - 0x00007FF845A0E802
10=???! ??? - 0x000001CA4FE69BD0
11=???! ??? - 0x000001CA32B56CC0
12=???! ??? - 0x000001CA4B71F76C
13=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll! ??? - 0x00007FF8A4D646B5, module offset(base): 0x46b5(0x7ff8a4d60000)
14=???! ??? - 0x00007FF845A0E1A6
15=???! ??? - 0x000001CA4FE69BD0
16=???! ??? - 0x0000003D5BEFE8C0
17=???! ??? - 0x000001CA4B71F26C
18=???! ??? - 0x000001CA4B71F9EC
19=???! ??? - 0x000001CA4B71F5DC
20=???! ??? - 0x000001CA4B71F76C
21=???! ??? - 0x000001CA4B71F62C
22=???! ??? - 0x0000003D5BEFE880
23=speechClient.dll! DllUnregisterServer - 0x00007FF8987613A8, module offset(base): 0xc13a8(0x7ff8986a0000)
24=???! ??? - 0x000001CA30A973E0
25=???! ??? - 0x000001CA4FE69BD0
26=???! ??? - 0x000001CA32A6EFC8
27=???! ??? - 0x000001CA32B56CC0
28=???! ??? - 0x000001CA4FBB4E50
29=???! ??? - 0x000001CA32B57098
30=???! ??? - 0x000001CA32CA5DB8
31=???! ??? - 0x0000003D5BEFE9B0
32=???! ??? - 0x00007FF845A0DACF
33=???! ??? - 0x000001CA32B56CC0
34=???! ??? - 0x000001CA32B56D58
35=???! ??? - 0x000060525372E2B2

**Comment by v-sukssi** [comment]
Could you please hare the detailed scenario where you are using it.

**Comment by leviyakir** [comment]
We have 2 separate audio streams of a conversation. We open a client for each and send the audio streams for transcription.

**Comment by priyaravi20** [comment]
Bing speech does not support multiple audios at the same time.

**Comment by leviyakir** [comment]
Is it possible to have multiple clients each in a separate process on the same machine?

**Comment by Plasma** [comment]
@priyaravi20 @leviyakir Yes I'm experiencing issues too. @priyaravi20 for clarity at least in my case I'm performing recognitions separately, one after another, never at the same time or during the same session -- I new up a new DataRecognitionClient each time.
