### ISSUE TITLE
Client Shut Down after some silences

### ISSUE THREAD

**Issue by melvinma** [Azure-Samples/Cognitive-Speech-STT-Windows#27]
I had this problem at least twice now. In the first instance, I have 30 seconds silences at the beginning and the client simply not doing anything for me. When I removed the silence at the beginning, it worked. 

In the second instance, it appears somehow it determined that the transcription should be ended at around 1 minute 45 seconds  and all the remaining transcripts are missing. 

I wonder what is the policy here and what I could do to prevent this. 
Thanks,

Melvin

**Comment by priyaravi20** [comment]
Hi Melvin - This is a defect in the SDK and will be addressed in the next release. I don't have a definite date. But will update this thread.

**Comment by priyaravi20** [comment]
Missing transcript issue has been fixed.
