### ISSUE TITLE
Abnormal dispose time after StartRec

### ISSUE THREAD

**Issue by Terminator24** [Azure-Samples/Cognitive-Speech-STT-Windows#30]
Hi,
with the latest library update (1.0.0.6, NuGet), i noticed that after calling -StartMicAndRecognition();-
the dispose() time takes about 2 to 3 secs.
This is weird because if you dispose the -MicrophoneRecognitionClient- just after the constructor, it only takes some milliseconds.
I followed the example and noticed that this happens in it too.
I remain available for any other information.
Thanks.

**Comment by priyaravi20** [comment]
Thanks for reporting. I was able to reproduce the delay in dispose and we will add the fix to next update.

**Comment by Impertatore** [comment]
I'm receiving the following warning after installing the latest version of 'Microsoft.ProjectOxford.SpeechRecognition; version 1.0.0.6'; it suggests that the assembly is not signed; where can I locate the signed version of this assembly?

CS8002: Referenced assembly 'SpeechClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name

**Comment by priyaravi20** [comment]
Hi - We will fix this in the next update. In the meantime as long as you get the SDK from official place in nuget this should not be a blocker I hope.

**Comment by MEK3DK** [comment]
I also have the problem with the "does not have a strong name" I use the nuget package.
It is a blocker for me, when it the next update?

**Comment by priyaravi20** [comment]
We are planning for an update in a month.

**Comment by priyaravi20** [comment]
Please get the latest update to get the strong name issue fix,

**Comment by Terminator24** [comment]
I just did the update, but it Still takes a lot of time when Disposing() etc.
