### ISSUE TITLE
How to increase Initial Silence Timeout in a WPF application using SpeechRecognizationServiceFactory

### ISSUE THREAD

**Issue by Milesbs** [Azure-Samples/Cognitive-Speech-STT-Windows#32]
Hi, 

I would like to increase the Initial Silence Timeout in my WPF application using SpeechRecognizationServiceFactory.
Right now, it seems to be set by default to a few seconds but i need it to be continuous.
Is it possible ?

Thanks

**Comment by priyaravi20** [comment]
Currently this is controlled from the service. TImeouts are different for short and long..You can try using long mode for a more continuous experience.
