### ISSUE TITLE
SpeechClient does not have a strong name

### ISSUE THREAD

**Issue by Impertatore** [Azure-Samples/Cognitive-Speech-STT-Windows#33]
--created a specific thread for this issue as it was nested in an unrelated post.

I'm receiving the following warning after installing the latest version of 'Microsoft.ProjectOxford.SpeechRecognition; version 1.0.0.6'; it suggests that the assembly is not signed; where can I locate the signed version of this assembly?
CS8002: Referenced assembly 'SpeechClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name

Unfortunately this is a blocker for me, preventing me from implementing any features that reference it.

Can we please have another update -> when we can expect to see this issue resolved?

**Comment by MEK3DK** [comment]
I also have the problem with the "does not have a strong name" I use the nuget package.
It is also a blocker for me, when is the next update?

**Comment by priyaravi20** [comment]
We should have one in a month's time.

**Comment by zhouwangzw** [comment]
A new version 1.0.0.7 has been published today. All assemblies in the package are now signed with a strong name.
