### ISSUE TITLE
Infinite Error Message Loop

### ISSUE THREAD

**Issue by Terminators24** [Azure-Samples/Cognitive-Speech-STT-Windows#34]
Hi, yesterday i noticed that my API Key expired.
(I use Microsoft.ProjectOxford.SpeechRecognition-x86.1.0.0.6 nuget version).

So, starting the the <<microphoneRecognitionClient.StartMicAndRecognition()>> causes an Infinite error message loop that shows in alternation <<Internal Error>> and <<Login failed>>.

So i decided to try to <<microphoneRecognitionClient.EndMicAndRecognition()>> in <<MicrophoneRecognitionClient_OnConversationError>> event and I noticed that the Infinite lopp ended after about 6/7 calls of the error event.

I think this is abnormal operation of the error event caller inside the library.

**Comment by wolfma61** [comment]
thank you for reporting this.
We will take a look and try to figure out what is going wrong ...
Wolfgang
