### ISSUE TITLE
The remote server returned an error: (401) Unauthorized

### ISSUE THREAD

**Issue by rodrigomocca** [Azure-Samples/Cognitive-Speech-STT-Windows#35]
Today I started receive The remote server returned an error: (401) Unauthorized error. My app is working since Cognitive Services was Project Oxford.
Now I'm getting this, and I can't find where I must login to get a new apiKey.

Everything I found on internet redirect me to Azure. I've never signed up to Azure to do this.
How do I fix this?

**Comment by rodrigomocca** [comment]
But I already have this apiKeys, but now it doesn't work.
Before I sign in without azure. Now I have to do it with Azure, but I don't have an azure account. So I've created one, but I don't see any cognitive services subscription.
How I recover my account with my previously payment methods loaded?

And why my app has stopped working now?
Why do you complicate things that much and with no notification?

I need to fix this right now, I have my system stopped because of this.

________________________________

**Comment by zhouwangzw** [comment]
@rodrigomocca Are you on a free tier or standard tier? If this is a free tier, does the usage exceedes the limit? More information can be found [here](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/speech-api/)

**Comment by rodrigomocca** [comment]
I don't know because I have not place to login and see my data.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by zhouwangzw** [comment]
@rodrigomocca  I am afraid that your API key is not valid any more for whatever reason. Could you please try the following script in Powershell, after replacing YOUR_API_KEY with the key you are using: 
```
$FetchTokenHeader = @{
'Content-type'='application/x-www-form-urlencoded';
'Content-Length'= '0';
'Ocp-Apim-Subscription-Key' = 'YOUR_API_KEY'
}

Invoke-RestMethod -Method POST -Uri https://api.cognitive.microsoft.com/sts/v1.0/issueToken -Headers $FetchTokenHeader
```
If you get an error, then your API key cannot be correctly authenticated. In this case, you may want to get a trial key using the [link](https://azure.microsoft.com/en-us/try/cognitive-services/), and then try the script above again.

**Comment by zhouwangzw** [comment]
I am closing the issue due to lack of reponse. Please feel free to reopen a new one if you still have the problem. 
Thanks,
