### ISSUE TITLE
How to complete a recognize loop

### ISSUE THREAD

**Issue by LGinC** [Azure-Samples/Cognitive-Speech-STT-Windows#37]
I use the Kinect v2 as microphone input device， and I want to use audio stream to complete auto recognition， like the Kinect SDK v2 Sample “Speech Basics”, I just speech without start Button.

**Comment by wolfma61** [comment]
what is the problem you are seeing?
Does Kinect generate the correct audio format?

from the docs: PCM audio **must** be sampled at 16 kHz with 16 bits per sample and one channel (*riff-16khz-16bit-mono-pcm*). The Microsoft Speech Service does not support
stereo audio streams and will reject audio streams that do not use the specified bit rate, sample rate or number of channels.

**Comment by LGinC** [comment]
the Kinect v2 audio format is sampled 16KHz, 32bit depth  and one channel, I have converted to 16bit depth, actually, it's work, but when I hadn't speech a while, I want to continue speech but it didn't work, there's any response

**Comment by zhouwangzw** [comment]
The connection will get closed after some period of inactivity. You need to set up the connection again to start a new recognition.
