### ISSUE TITLE
LoginFailed, transport error

### ISSUE THREAD

**Issue by ramicodes** [Azure-Samples/Cognitive-Speech-STT-Windows#38]
I followed the steps listed in the instructions, ran the sample and got the following error: 
Error code: LoginFailed

Also, what value will the sample need for the AuthenticationUri key in app.config
<add key="AuthenticationUri" value="" />

**Comment by raaaar** [comment]
AuthenticationUri is an optional parameter, default value is "https://api.cognitive.microsoft.com/sts/v1.0/issueToken". Were you able to solve the login issue by changing the uri?

**Comment by ramicodes** [comment]
still the same issue:
 Error received by OnConversationErrorHandler() ---
Error code: LoginFailed
Error text: Transport erro

**Comment by ramicodes** [comment]
is there no place to put the key for the speech API?

**Comment by raaaar** [comment]
There's a text field in the right upper corner of the Sample where the key is supposed to go. Could you also try the REST API (https://github.com/Azure-Samples/SpeechToText-REST/blob/master/curl/transcribe.bat):

`transcribe.bat <key> <wav file>`

**Comment by pravinkl** [comment]
Do we have a solution for this issue?

**Comment by zhouwangzw** [comment]
We can repro the issue and we are currently looking into it.

**Comment by zhouwangzw** [comment]
I can now run the sample without seeing the error above. Could you please try again? If you still have the problem, could you check whether your subscription key is expired or exceeds the quota (in case you are using a free trial key)?

**Comment by pereiraguilherme** [comment]
I'm also having the same issue as @ramicodes had. I'm using a valid key and already tried the two keys given by Azure account. If you guys, solve this issue, let me know! Thanks!

**Comment by zhouwangzw** [comment]
@pereiraguilherme Could you please follow the steps described in [Authentication for using the service](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/how-to/how-to-authentication?tabs=Powershell) to check whether you can get an Authorization token using one of you keys? Please note you need to verify for authorization token, but not just for subscription key. Could you please post error message in case of failure?

**Comment by zhouwangzw** [comment]
@pereiraguilherme And if can get an authorization token successfully using REST, then could you please check whether you have past the same subscription key in the text edit box and save it? On which platform, x86 or x64 are you running your sample?

**Comment by shayben** [comment]
@zhouwangzw did you verify that it works with the client libraries as well? Or just the REST api?
I still see this issue.

**Comment by zhouwangzw** [comment]
I just ran the SpeechToText-WPF-Sample again, using my subscription key, and it works fine.
You can check whether your key is still vaid by clicking on "Log in" at the page "[Try Cognitive Services](https://azure.microsoft.com/en-us/try/cognitive-services/)" (at the right side of the tab "Vision/Speech/Language/Knowledge/Search"), using the account you used to get the subscription key.

**Comment by shayben** [comment]
@zhouwangzw I only see my trial account on that page, which is expired. 
I do have a subscription and am using the correct subscription key (tried regenerating it as well), and still get the transport error message in the SpeechToText-WPF-Sample.

**Comment by zhouwangzw** [comment]
@shayben Do you mean that your trial account is expired? Could you please check whether your subscription key is expired too? It is only valid for a certain period of time and has a quota assoicated. Can you try to run the REST example, as described [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedrest?tabs=Powershell) with your key?

**Comment by zhouwangzw** [comment]
I am closing the isseu due to lack of response. Please open a new one if you still have issues.

**Comment by SanaWaseem** [comment]
@miloush  how to resolve it

**Comment by miloush** [comment]
@SanaWaseem if you want to use cognitive services, don't use this sample. Use the one I linked to.

**Comment by SanaWaseem** [comment]
@miloush Can you please mention it?
