### ISSUE TITLE
There is any response after Results.length = 0

### ISSUE THREAD

**Issue by LGinC** [Azure-Samples/Cognitive-Speech-STT-Windows#39]
`private void Recognizer_OnResponseReceived(object sender, SpeechResponseEventArgs e)
        {

            if (e.PhraseResponse.Results.Length == 0)
            {
                Console.WriteLine("No phrase response is available.");
            }
            else
            {
                Console.WriteLine("********* Final n-BEST Results *********");
                for (int i = 0; i < e.PhraseResponse.Results.Length; i++)
                {
                    Console.WriteLine( "[{0}] Confidence={1}, Text=\"{2}\"", i, e.PhraseResponse.Results[i].Confidence, e.PhraseResponse.Results[i].DisplayText);
                }
                Console.WriteLine();
            }
        }`
after console output the "No phrase response is available", I speech but no recognition  result.

**Comment by georgiak22** [comment]
Having the same issue, did you resolve it somehow?

**Comment by priyaravi20** [comment]
If there is no recognition result coming back you get this message.  Please make sure to use the correct audio format - we support pcm in .wav.
