### ISSUE TITLE
SpeechClient.dll for UWP apps?

### ISSUE THREAD

**Issue by haiyan** [Azure-Samples/Cognitive-Speech-STT-Windows#40]
Hi, is it possible to get a build of the SpeechClient.dll targeted at .NETCore or a Portable Library so it can be used in a UWP app?

I want to use Audiograph in conjunction with the Speech API.

Thanks!

**Comment by zhouwangzw** [comment]
We are working a new version of C# Client SDK, which will be .NET Standard 2.0 and UWP compatible. But we do not have an ETA for release yet.

**Comment by TiMeJuMp** [comment]
Is there a solution for given context? 
I also need the SpeecClient.dll for connecting Microphone Input directly with LUIS to get the best matches in one step.
Thanks for help,

**Comment by zhouwangzw** [comment]
The current C# client library supports integration with LUIS, but it only works on desktop. The 1.0.0.7 release supports  also the new LUIS app endpoint.

**Comment by TiMeJuMp** [comment]
Do you know when an update will be released to make it compatible with UWP?

**Comment by haiyan** [comment]
I couldn’t wait for the UWP release, so wrote my own class. Will write a blog entry about it and share - fairly lightweight. Excited for the dll version !

**Comment by devedse** [comment]
@zhouwangzw Is there already an ETA available on when the rewrite will be completed? Furthermore I think it might be good to leave this issue open and add a note to the readme on the main page that there's currently no C# SDK available for the Custom speech api in C#

**Comment by wolfma61** [comment]
it will be April/May

**Comment by nrweber** [comment]
@wolfma61 and @zhouwangzw :  Any update on when the .NET Standard version is coming?

**Comment by wolfma61** [comment]
we just released the new Speech Service last week (https://docs.microsoft.com/de-de/azure/cognitive-services/speech-service/)
there will be an initial refresh early June with improvements/bug fixes. I would hope the next refresh will help (late June/early July)
