### ISSUE TITLE
.net Core implementation of the speechclient.dll

### ISSUE THREAD

**Issue by lokeshkumarn** [Azure-Samples/Cognitive-Speech-STT-Windows#43]
How to use the SpeechClient.dll in .net core web app

**Comment by priyaravi20** [comment]
Not possible with this library. We will releasing another SDK early nest year to address this issue.

**Comment by lokeshkumarn** [comment]
Thank you
I was trying to use it Web api but I am getting C++ module failed to load, is that because it is being used in .net core

**Comment by lokeshkumarn** [comment]
Even in Web API 2.0 its not working
[BadImageFormatException: Could not load file or assembly 'SpeechClient' or one of its dependencies. An attempt was made to load a program with an incorrect format.]
   System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0
   System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +36
   System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +152
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +77
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +21
   System.Reflection.Assembly.Load(String assemblyString) +28
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +38

**Comment by zhouwangzw** [comment]
For using with Web API, could you please try C# Service Library? It should work with Web API, but probably not with WebCore. We are currently working on a new version which supports WebCore.

**Comment by lokeshkumarn** [comment]
Service library not responding
wss://xxxxxxxxxxxxxxxxxxxxxxxx.api.cris.ai/speech/recognition/interactive/cognitiveservices/v1
